# Web Server Config
server:
  port: ${SPRING_PORT:8038}

# Spring App Config
spring:
  application:
    name: ${SPRING_APPNAME:whocalledmeservice}
  messages:
    basename: messages/messages
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${SPRING_EUREKA_SERVER:localhost}:${SPRING_EUREKA_PORT:8761}/eureka
